## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv(r"C:\Users\stell\OneDrive\Desktop\Analysis Projects\World_Weather_Analysis\Weather_Database\WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Busselton,AU,-33.6500,115.3333,73.96,41,0,2.98,clear sky
1,1,Quang Ngai,VN,15.1167,108.8000,68.72,94,100,6.24,overcast clouds
2,2,Saint-Augustin,CA,51.2260,-58.6502,-2.96,86,100,7.90,overcast clouds
3,3,Norman Wells,CA,65.2820,-126.8329,-12.96,64,75,21.85,broken clouds
4,4,Jasper,US,37.2001,-94.3502,29.01,50,0,1.99,clear sky

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
5,5,Kapaa,US,22.0752,-159.3190,80.47,69,0,1.99,clear sky
7,7,Maroantsetra,MG,-15.4333,49.7333,76.66,81,100,6.82,overcast clouds
9,9,Souillac,MU,-20.5167,57.5167,79.36,94,75,11.50,light rain
11,11,Rikitea,PF,-23.1203,-134.9692,78.55,71,10,7.87,light rain
17,17,Kahului,US,20.8947,-156.4700,83.46,69,20,11.50,few clouds
21,21,Atuona,PF,-9.8000,-139.0333,78.66,76,23,16.62,light rain
24,24,Avarua,CK,-21.2078,-159.7750,84.25,74,75,14.97,broken clouds
28,28,Caravelas,BR,-17.7125,-39.2481,77.09,88,100,8.12,overcast clouds
31,31,Puerto Ayora,EC,-0.7393,-90.3518,77.56,89,83,5.99,broken clouds
50,50,Yambio,SS,4.5721,28.3955,75.18,28,100,2.17,overcast clouds

In [9]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.count()

City_ID                160
City                   160
Country                160
Lat                    160
Lng                    160
Max Temp               160
Humidity               160
Cloudiness             160
Wind Speed             160
Current Description    160
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,80.47,clear sky,22.0752,-159.3190,
7,Maroantsetra,MG,76.66,overcast clouds,-15.4333,49.7333,
9,Souillac,MU,79.36,light rain,-20.5167,57.5167,
11,Rikitea,PF,78.55,light rain,-23.1203,-134.9692,
17,Kahului,US,83.46,few clouds,20.8947,-156.4700,
21,Atuona,PF,78.66,light rain,-9.8000,-139.0333,
24,Avarua,CK,84.25,broken clouds,-21.2078,-159.7750,
28,Caravelas,BR,77.09,overcast clouds,-17.7125,-39.2481,
31,Puerto Ayora,EC,77.56,broken clouds,-0.7393,-90.3518,
50,Yambio,SS,75.18,overcast clouds,4.5721,28.3955,

In [11]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat}, {lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
   
    hotels = requests.get(base_url, params = params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")

Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.

In [12]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df.dropna()

clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Kapaa,US,80.47,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
7,Maroantsetra,MG,76.66,overcast clouds,-15.4333,49.7333,Annexe Vatsy Hôtel
9,Souillac,MU,79.36,light rain,-20.5167,57.5167,Shanti Maurice Resort & Spa
11,Rikitea,PF,78.55,light rain,-23.1203,-134.9692,People ThankYou
17,Kahului,US,83.46,few clouds,20.8947,-156.4700,Maui Seaside Hotel
21,Atuona,PF,78.66,light rain,-9.8000,-139.0333,Villa Enata
24,Avarua,CK,84.25,broken clouds,-21.2078,-159.7750,Paradise Inn
28,Caravelas,BR,77.09,overcast clouds,-17.7125,-39.2481,Pousada dos Navegantes
31,Puerto Ayora,EC,77.56,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
50,Yambio,SS,75.18,overcast clouds,4.5721,28.3955,Naivasha Hotel

In [13]:
# 8a. Create the output File (CSV)

output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv

clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [17]:
# 11a. Add a marker layer for each city to the map. 

max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))